# Generated by Django 5.2 on 2025-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Mobile_no', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('DoB', models.DateField()),
                ('Loan_amount', models.IntegerField()),
            ],
        ),
    ]
